baseURL = 'https://skytang0205.github.io'
title = 'Zero'

# multi-language support
defaultContentLanguage = 'en'

# enable git info
enableGitInfo = true

# disable taxonomy, term and RSS (which removes categories, tags and index.xml)
disableKinds = ["taxonomy", "term", "RSS"]

[module]
  [[module.imports]]
    path = 'github.com/geekifan/zero-academic-page'

[languages]
  [languages.en]
    languageName = 'English'
    weight = 1
    title = 'Zero'

    [languages.en.params]
      author = "Yizao Tang"
      description = "Student in [Peking University](https://pku.edu.com). Focusing on Computer Graphics and Physically-based Visual Computing."
      motto = "All tragedy erased, I see only wonders."
    
    [[languages.en.menu.main]]
      name = 'About Me'
      url = '#about-me'
      weight = 1
    [[languages.en.menu.main]]
      name = 'News'
      url = '#news'
      weight = 2
    [[languages.en.menu.main]]
      name = 'Publications'
      url = '#publications'
      weight = 3
    [[languages.en.menu.main]]
      name = 'Educations'
      url = '#educations'
      weight = 5
      
[params]
  profilePicture = "images/avatar.png"
  enableDarkMode = true
  
  [[params.social]]
    name = "github"
    url = "https://github.com/skytang0205/"
    icon = "fab fa-fw fa-github"
  [[params.social]]
    name = "email"
    url = "skytang0205@outlook.com"
    icon = "fas fa-fw fa-envelope"
  [[params.social]]
    name = "steam"
    url = "skytang0205@outlook.com"
    icon = "fab fa-fw fa-steam-square"
  [[params.social]]
    name = "twitter"
    url = "https://x.com/skytang0205"
    icon = "fab fa-fw fa-twitter-square"
    

[build]
  writeStats = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
